// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: service/packet_router.proto

package packet_router

import (
	helium "github.com/thisisdevelopment/helium-route-updater/pkg/api/helium"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketRouterPacketReportV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewayTimestampMs uint64 `protobuf:"varint,1,opt,name=gateway_timestamp_ms,json=gatewayTimestampMs,proto3" json:"gateway_timestamp_ms,omitempty"`
	Oui                uint64 `protobuf:"varint,2,opt,name=oui,proto3" json:"oui,omitempty"`
	NetId              uint32 `protobuf:"varint,3,opt,name=net_id,json=netId,proto3" json:"net_id,omitempty"`
	// signal strength in dBm
	Rssi int32 `protobuf:"zigzag32,4,opt,name=rssi,proto3" json:"rssi,omitempty"`
	// Frequency in hz
	Frequency uint32          `protobuf:"varint,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Snr       float32         `protobuf:"fixed32,6,opt,name=snr,proto3" json:"snr,omitempty"`
	Datarate  helium.DataRate `protobuf:"varint,7,opt,name=datarate,proto3,enum=helium.DataRate" json:"datarate,omitempty"`
	Region    helium.Region   `protobuf:"varint,8,opt,name=region,proto3,enum=helium.Region" json:"region,omitempty"`
	Gateway   []byte          `protobuf:"bytes,9,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Hash of `payload` within `message packet`
	PayloadHash []byte `protobuf:"bytes,10,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	PayloadSize uint32 `protobuf:"varint,11,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
}

func (x *PacketRouterPacketReportV1) Reset() {
	*x = PacketRouterPacketReportV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_packet_router_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketRouterPacketReportV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketRouterPacketReportV1) ProtoMessage() {}

func (x *PacketRouterPacketReportV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_packet_router_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketRouterPacketReportV1.ProtoReflect.Descriptor instead.
func (*PacketRouterPacketReportV1) Descriptor() ([]byte, []int) {
	return file_service_packet_router_proto_rawDescGZIP(), []int{0}
}

func (x *PacketRouterPacketReportV1) GetGatewayTimestampMs() uint64 {
	if x != nil {
		return x.GatewayTimestampMs
	}
	return 0
}

func (x *PacketRouterPacketReportV1) GetOui() uint64 {
	if x != nil {
		return x.Oui
	}
	return 0
}

func (x *PacketRouterPacketReportV1) GetNetId() uint32 {
	if x != nil {
		return x.NetId
	}
	return 0
}

func (x *PacketRouterPacketReportV1) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *PacketRouterPacketReportV1) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *PacketRouterPacketReportV1) GetSnr() float32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

func (x *PacketRouterPacketReportV1) GetDatarate() helium.DataRate {
	if x != nil {
		return x.Datarate
	}
	return helium.DataRate(0)
}

func (x *PacketRouterPacketReportV1) GetRegion() helium.Region {
	if x != nil {
		return x.Region
	}
	return helium.Region(0)
}

func (x *PacketRouterPacketReportV1) GetGateway() []byte {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *PacketRouterPacketReportV1) GetPayloadHash() []byte {
	if x != nil {
		return x.PayloadHash
	}
	return nil
}

func (x *PacketRouterPacketReportV1) GetPayloadSize() uint32 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

type PacketRouterPacketUpV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload   []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// signal strength in dBm
	Rssi int32 `protobuf:"zigzag32,3,opt,name=rssi,proto3" json:"rssi,omitempty"`
	// Frequency in hz
	Frequency uint32          `protobuf:"varint,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Datarate  helium.DataRate `protobuf:"varint,5,opt,name=datarate,proto3,enum=helium.DataRate" json:"datarate,omitempty"`
	Snr       float32         `protobuf:"fixed32,6,opt,name=snr,proto3" json:"snr,omitempty"`
	Region    helium.Region   `protobuf:"varint,7,opt,name=region,proto3,enum=helium.Region" json:"region,omitempty"`
	HoldTime  uint64          `protobuf:"varint,8,opt,name=hold_time,json=holdTime,proto3" json:"hold_time,omitempty"`
	Gateway   []byte          `protobuf:"bytes,9,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Signature []byte          `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *PacketRouterPacketUpV1) Reset() {
	*x = PacketRouterPacketUpV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_packet_router_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketRouterPacketUpV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketRouterPacketUpV1) ProtoMessage() {}

func (x *PacketRouterPacketUpV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_packet_router_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketRouterPacketUpV1.ProtoReflect.Descriptor instead.
func (*PacketRouterPacketUpV1) Descriptor() ([]byte, []int) {
	return file_service_packet_router_proto_rawDescGZIP(), []int{1}
}

func (x *PacketRouterPacketUpV1) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PacketRouterPacketUpV1) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PacketRouterPacketUpV1) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *PacketRouterPacketUpV1) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *PacketRouterPacketUpV1) GetDatarate() helium.DataRate {
	if x != nil {
		return x.Datarate
	}
	return helium.DataRate(0)
}

func (x *PacketRouterPacketUpV1) GetSnr() float32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

func (x *PacketRouterPacketUpV1) GetRegion() helium.Region {
	if x != nil {
		return x.Region
	}
	return helium.Region(0)
}

func (x *PacketRouterPacketUpV1) GetHoldTime() uint64 {
	if x != nil {
		return x.HoldTime
	}
	return 0
}

func (x *PacketRouterPacketUpV1) GetGateway() []byte {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *PacketRouterPacketUpV1) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PacketRouterRegisterV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Gateway   []byte `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *PacketRouterRegisterV1) Reset() {
	*x = PacketRouterRegisterV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_packet_router_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketRouterRegisterV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketRouterRegisterV1) ProtoMessage() {}

func (x *PacketRouterRegisterV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_packet_router_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketRouterRegisterV1.ProtoReflect.Descriptor instead.
func (*PacketRouterRegisterV1) Descriptor() ([]byte, []int) {
	return file_service_packet_router_proto_rawDescGZIP(), []int{2}
}

func (x *PacketRouterRegisterV1) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PacketRouterRegisterV1) GetGateway() []byte {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *PacketRouterRegisterV1) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type EnvelopeUpV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*EnvelopeUpV1_Register
	//	*EnvelopeUpV1_Packet
	Data isEnvelopeUpV1_Data `protobuf_oneof:"data"`
}

func (x *EnvelopeUpV1) Reset() {
	*x = EnvelopeUpV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_packet_router_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvelopeUpV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeUpV1) ProtoMessage() {}

func (x *EnvelopeUpV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_packet_router_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeUpV1.ProtoReflect.Descriptor instead.
func (*EnvelopeUpV1) Descriptor() ([]byte, []int) {
	return file_service_packet_router_proto_rawDescGZIP(), []int{3}
}

func (m *EnvelopeUpV1) GetData() isEnvelopeUpV1_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *EnvelopeUpV1) GetRegister() *PacketRouterRegisterV1 {
	if x, ok := x.GetData().(*EnvelopeUpV1_Register); ok {
		return x.Register
	}
	return nil
}

func (x *EnvelopeUpV1) GetPacket() *PacketRouterPacketUpV1 {
	if x, ok := x.GetData().(*EnvelopeUpV1_Packet); ok {
		return x.Packet
	}
	return nil
}

type isEnvelopeUpV1_Data interface {
	isEnvelopeUpV1_Data()
}

type EnvelopeUpV1_Register struct {
	Register *PacketRouterRegisterV1 `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type EnvelopeUpV1_Packet struct {
	Packet *PacketRouterPacketUpV1 `protobuf:"bytes,2,opt,name=packet,proto3,oneof"`
}

func (*EnvelopeUpV1_Register) isEnvelopeUpV1_Data() {}

func (*EnvelopeUpV1_Packet) isEnvelopeUpV1_Data() {}

type WindowV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Frequency in hz
	Frequency uint32          `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Datarate  helium.DataRate `protobuf:"varint,3,opt,name=datarate,proto3,enum=helium.DataRate" json:"datarate,omitempty"`
}

func (x *WindowV1) Reset() {
	*x = WindowV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_packet_router_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WindowV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowV1) ProtoMessage() {}

func (x *WindowV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_packet_router_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowV1.ProtoReflect.Descriptor instead.
func (*WindowV1) Descriptor() ([]byte, []int) {
	return file_service_packet_router_proto_rawDescGZIP(), []int{4}
}

func (x *WindowV1) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WindowV1) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *WindowV1) GetDatarate() helium.DataRate {
	if x != nil {
		return x.Datarate
	}
	return helium.DataRate(0)
}

type PacketRouterPacketDownV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Rx1     *WindowV1 `protobuf:"bytes,2,opt,name=rx1,proto3" json:"rx1,omitempty"`
	Rx2     *WindowV1 `protobuf:"bytes,3,opt,name=rx2,proto3" json:"rx2,omitempty"`
}

func (x *PacketRouterPacketDownV1) Reset() {
	*x = PacketRouterPacketDownV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_packet_router_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketRouterPacketDownV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketRouterPacketDownV1) ProtoMessage() {}

func (x *PacketRouterPacketDownV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_packet_router_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketRouterPacketDownV1.ProtoReflect.Descriptor instead.
func (*PacketRouterPacketDownV1) Descriptor() ([]byte, []int) {
	return file_service_packet_router_proto_rawDescGZIP(), []int{5}
}

func (x *PacketRouterPacketDownV1) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PacketRouterPacketDownV1) GetRx1() *WindowV1 {
	if x != nil {
		return x.Rx1
	}
	return nil
}

func (x *PacketRouterPacketDownV1) GetRx2() *WindowV1 {
	if x != nil {
		return x.Rx2
	}
	return nil
}

type EnvelopeDownV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*EnvelopeDownV1_Packet
	Data isEnvelopeDownV1_Data `protobuf_oneof:"data"`
}

func (x *EnvelopeDownV1) Reset() {
	*x = EnvelopeDownV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_packet_router_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvelopeDownV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeDownV1) ProtoMessage() {}

func (x *EnvelopeDownV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_packet_router_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeDownV1.ProtoReflect.Descriptor instead.
func (*EnvelopeDownV1) Descriptor() ([]byte, []int) {
	return file_service_packet_router_proto_rawDescGZIP(), []int{6}
}

func (m *EnvelopeDownV1) GetData() isEnvelopeDownV1_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *EnvelopeDownV1) GetPacket() *PacketRouterPacketDownV1 {
	if x, ok := x.GetData().(*EnvelopeDownV1_Packet); ok {
		return x.Packet
	}
	return nil
}

type isEnvelopeDownV1_Data interface {
	isEnvelopeDownV1_Data()
}

type EnvelopeDownV1_Packet struct {
	Packet *PacketRouterPacketDownV1 `protobuf:"bytes,1,opt,name=packet,proto3,oneof"`
}

func (*EnvelopeDownV1_Packet) isEnvelopeDownV1_Data() {}

var File_service_packet_router_proto protoreflect.FileDescriptor

var file_service_packet_router_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x68,
	0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x1a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xf6, 0x02, 0x0a, 0x1e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x5f, 0x76, 0x31, 0x12, 0x30, 0x0a, 0x14, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x12, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75, 0x69, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6f, 0x75, 0x69, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x65, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6e, 0x65, 0x74, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x73, 0x73, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x11, 0x52, 0x04,
	0x72, 0x73, 0x73, 0x69, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6e, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x03, 0x73, 0x6e, 0x72, 0x12, 0x2d, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x72, 0x61, 0x74, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x72,
	0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x48, 0x61, 0x73, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xc4, 0x02, 0x0a, 0x1a,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x5f, 0x75, 0x70, 0x5f, 0x76, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x73, 0x73, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x11,
	0x52, 0x04, 0x72, 0x73, 0x73, 0x69, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x2d, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x72, 0x61, 0x74, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x72,
	0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6e, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x03, 0x73, 0x6e, 0x72, 0x12, 0x26, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a,
	0x09, 0x68, 0x6f, 0x6c, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x68, 0x6f, 0x6c, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x22, 0x71, 0x0a, 0x19, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xb3, 0x01, 0x0a, 0x0e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x5f, 0x75, 0x70, 0x5f, 0x76, 0x31, 0x12, 0x4d, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x68, 0x65, 0x6c,
	0x69, 0x75, 0x6d, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x5f,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x48, 0x00, 0x52, 0x08, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d,
	0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x5f, 0x75, 0x70, 0x5f, 0x76, 0x31, 0x48, 0x00, 0x52, 0x06, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x76, 0x0a, 0x09, 0x77,
	0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x76, 0x31, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x2d, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x72, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x72,
	0x61, 0x74, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x1c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x64, 0x6f, 0x77,
	0x6e, 0x5f, 0x76, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x31,
	0x0a, 0x03, 0x72, 0x78, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x65,
	0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x76, 0x31, 0x52, 0x03, 0x72, 0x78,
	0x31, 0x12, 0x31, 0x0a, 0x03, 0x72, 0x78, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x76, 0x31, 0x52,
	0x03, 0x72, 0x78, 0x32, 0x22, 0x68, 0x0a, 0x10, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x76, 0x31, 0x12, 0x4c, 0x0a, 0x06, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75,
	0x6d, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x76, 0x31, 0x48, 0x00, 0x52, 0x06,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x63,
	0x0a, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x59, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x12, 0x24, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x5f, 0x75, 0x70, 0x5f, 0x76, 0x31, 0x1a, 0x26, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d,
	0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x65,
	0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x76, 0x31, 0x28,
	0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_packet_router_proto_rawDescOnce sync.Once
	file_service_packet_router_proto_rawDescData = file_service_packet_router_proto_rawDesc
)

func file_service_packet_router_proto_rawDescGZIP() []byte {
	file_service_packet_router_proto_rawDescOnce.Do(func() {
		file_service_packet_router_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_packet_router_proto_rawDescData)
	})
	return file_service_packet_router_proto_rawDescData
}

var file_service_packet_router_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_packet_router_proto_goTypes = []interface{}{
	(*PacketRouterPacketReportV1)(nil), // 0: helium.packet_router.packet_router_packet_report_v1
	(*PacketRouterPacketUpV1)(nil),     // 1: helium.packet_router.packet_router_packet_up_v1
	(*PacketRouterRegisterV1)(nil),     // 2: helium.packet_router.packet_router_register_v1
	(*EnvelopeUpV1)(nil),               // 3: helium.packet_router.envelope_up_v1
	(*WindowV1)(nil),                   // 4: helium.packet_router.window_v1
	(*PacketRouterPacketDownV1)(nil),   // 5: helium.packet_router.packet_router_packet_down_v1
	(*EnvelopeDownV1)(nil),             // 6: helium.packet_router.envelope_down_v1
	(helium.DataRate)(0),               // 7: helium.data_rate
	(helium.Region)(0),                 // 8: helium.region
}
var file_service_packet_router_proto_depIdxs = []int32{
	7,  // 0: helium.packet_router.packet_router_packet_report_v1.datarate:type_name -> helium.data_rate
	8,  // 1: helium.packet_router.packet_router_packet_report_v1.region:type_name -> helium.region
	7,  // 2: helium.packet_router.packet_router_packet_up_v1.datarate:type_name -> helium.data_rate
	8,  // 3: helium.packet_router.packet_router_packet_up_v1.region:type_name -> helium.region
	2,  // 4: helium.packet_router.envelope_up_v1.register:type_name -> helium.packet_router.packet_router_register_v1
	1,  // 5: helium.packet_router.envelope_up_v1.packet:type_name -> helium.packet_router.packet_router_packet_up_v1
	7,  // 6: helium.packet_router.window_v1.datarate:type_name -> helium.data_rate
	4,  // 7: helium.packet_router.packet_router_packet_down_v1.rx1:type_name -> helium.packet_router.window_v1
	4,  // 8: helium.packet_router.packet_router_packet_down_v1.rx2:type_name -> helium.packet_router.window_v1
	5,  // 9: helium.packet_router.envelope_down_v1.packet:type_name -> helium.packet_router.packet_router_packet_down_v1
	3,  // 10: helium.packet_router.packet.route:input_type -> helium.packet_router.envelope_up_v1
	6,  // 11: helium.packet_router.packet.route:output_type -> helium.packet_router.envelope_down_v1
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_service_packet_router_proto_init() }
func file_service_packet_router_proto_init() {
	if File_service_packet_router_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_packet_router_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketRouterPacketReportV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_packet_router_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketRouterPacketUpV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_packet_router_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketRouterRegisterV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_packet_router_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvelopeUpV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_packet_router_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WindowV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_packet_router_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketRouterPacketDownV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_packet_router_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvelopeDownV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_packet_router_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*EnvelopeUpV1_Register)(nil),
		(*EnvelopeUpV1_Packet)(nil),
	}
	file_service_packet_router_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*EnvelopeDownV1_Packet)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_packet_router_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_packet_router_proto_goTypes,
		DependencyIndexes: file_service_packet_router_proto_depIdxs,
		MessageInfos:      file_service_packet_router_proto_msgTypes,
	}.Build()
	File_service_packet_router_proto = out.File
	file_service_packet_router_proto_rawDesc = nil
	file_service_packet_router_proto_goTypes = nil
	file_service_packet_router_proto_depIdxs = nil
}
