// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: service/packet_verifier.proto

package packet_verifier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvalidPacketReason int32

const (
	InvalidPacketReason_invalid_packet_reason_insufficient_balance InvalidPacketReason = 0
)

// Enum value maps for InvalidPacketReason.
var (
	InvalidPacketReason_name = map[int32]string{
		0: "invalid_packet_reason_insufficient_balance",
	}
	InvalidPacketReason_value = map[string]int32{
		"invalid_packet_reason_insufficient_balance": 0,
	}
)

func (x InvalidPacketReason) Enum() *InvalidPacketReason {
	p := new(InvalidPacketReason)
	*p = x
	return p
}

func (x InvalidPacketReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvalidPacketReason) Descriptor() protoreflect.EnumDescriptor {
	return file_service_packet_verifier_proto_enumTypes[0].Descriptor()
}

func (InvalidPacketReason) Type() protoreflect.EnumType {
	return &file_service_packet_verifier_proto_enumTypes[0]
}

func (x InvalidPacketReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvalidPacketReason.Descriptor instead.
func (InvalidPacketReason) EnumDescriptor() ([]byte, []int) {
	return file_service_packet_verifier_proto_rawDescGZIP(), []int{0}
}

type ValidPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayloadSize uint32 `protobuf:"varint,1,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	Gateway     []byte `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	PayloadHash []byte `protobuf:"bytes,3,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
}

func (x *ValidPacket) Reset() {
	*x = ValidPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_packet_verifier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidPacket) ProtoMessage() {}

func (x *ValidPacket) ProtoReflect() protoreflect.Message {
	mi := &file_service_packet_verifier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidPacket.ProtoReflect.Descriptor instead.
func (*ValidPacket) Descriptor() ([]byte, []int) {
	return file_service_packet_verifier_proto_rawDescGZIP(), []int{0}
}

func (x *ValidPacket) GetPayloadSize() uint32 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *ValidPacket) GetGateway() []byte {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *ValidPacket) GetPayloadHash() []byte {
	if x != nil {
		return x.PayloadHash
	}
	return nil
}

type InvalidPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayloadSize uint32              `protobuf:"varint,1,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	Gateway     []byte              `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	PayloadHash []byte              `protobuf:"bytes,3,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	Reason      InvalidPacketReason `protobuf:"varint,4,opt,name=reason,proto3,enum=helium.packet_verifier.InvalidPacketReason" json:"reason,omitempty"`
}

func (x *InvalidPacket) Reset() {
	*x = InvalidPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_packet_verifier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvalidPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidPacket) ProtoMessage() {}

func (x *InvalidPacket) ProtoReflect() protoreflect.Message {
	mi := &file_service_packet_verifier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidPacket.ProtoReflect.Descriptor instead.
func (*InvalidPacket) Descriptor() ([]byte, []int) {
	return file_service_packet_verifier_proto_rawDescGZIP(), []int{1}
}

func (x *InvalidPacket) GetPayloadSize() uint32 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *InvalidPacket) GetGateway() []byte {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *InvalidPacket) GetPayloadHash() []byte {
	if x != nil {
		return x.PayloadHash
	}
	return nil
}

func (x *InvalidPacket) GetReason() InvalidPacketReason {
	if x != nil {
		return x.Reason
	}
	return InvalidPacketReason_invalid_packet_reason_insufficient_balance
}

var File_service_packet_verifier_proto protoreflect.FileDescriptor

var file_service_packet_verifier_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x16, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x6e, 0x0a, 0x0c, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x48, 0x61, 0x73, 0x68, 0x22, 0xb7, 0x01, 0x0a, 0x0e, 0x69, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x61, 0x73, 0x68, 0x12, 0x45, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x68, 0x65, 0x6c,
	0x69, 0x75, 0x6d, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x2e, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x2a, 0x47, 0x0a, 0x15, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x2a, 0x69, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x73, 0x75, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x10, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_service_packet_verifier_proto_rawDescOnce sync.Once
	file_service_packet_verifier_proto_rawDescData = file_service_packet_verifier_proto_rawDesc
)

func file_service_packet_verifier_proto_rawDescGZIP() []byte {
	file_service_packet_verifier_proto_rawDescOnce.Do(func() {
		file_service_packet_verifier_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_packet_verifier_proto_rawDescData)
	})
	return file_service_packet_verifier_proto_rawDescData
}

var file_service_packet_verifier_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_packet_verifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_packet_verifier_proto_goTypes = []interface{}{
	(InvalidPacketReason)(0), // 0: helium.packet_verifier.invalid_packet_reason
	(*ValidPacket)(nil),      // 1: helium.packet_verifier.valid_packet
	(*InvalidPacket)(nil),    // 2: helium.packet_verifier.invalid_packet
}
var file_service_packet_verifier_proto_depIdxs = []int32{
	0, // 0: helium.packet_verifier.invalid_packet.reason:type_name -> helium.packet_verifier.invalid_packet_reason
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_packet_verifier_proto_init() }
func file_service_packet_verifier_proto_init() {
	if File_service_packet_verifier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_packet_verifier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_packet_verifier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvalidPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_packet_verifier_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_packet_verifier_proto_goTypes,
		DependencyIndexes: file_service_packet_verifier_proto_depIdxs,
		EnumInfos:         file_service_packet_verifier_proto_enumTypes,
		MessageInfos:      file_service_packet_verifier_proto_msgTypes,
	}.Build()
	File_service_packet_verifier_proto = out.File
	file_service_packet_verifier_proto_rawDesc = nil
	file_service_packet_verifier_proto_goTypes = nil
	file_service_packet_verifier_proto_depIdxs = nil
}
