// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: blockchain_txn_rewards_v1.proto

package helium

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockchainTxnRewardV1_Type int32

const (
	BlockchainTxnRewardV1_securities      BlockchainTxnRewardV1_Type = 0
	BlockchainTxnRewardV1_data_credits    BlockchainTxnRewardV1_Type = 1
	BlockchainTxnRewardV1_poc_challengees BlockchainTxnRewardV1_Type = 2
	BlockchainTxnRewardV1_poc_challengers BlockchainTxnRewardV1_Type = 3
	BlockchainTxnRewardV1_poc_witnesses   BlockchainTxnRewardV1_Type = 4
	BlockchainTxnRewardV1_consensus       BlockchainTxnRewardV1_Type = 5
)

// Enum value maps for BlockchainTxnRewardV1_Type.
var (
	BlockchainTxnRewardV1_Type_name = map[int32]string{
		0: "securities",
		1: "data_credits",
		2: "poc_challengees",
		3: "poc_challengers",
		4: "poc_witnesses",
		5: "consensus",
	}
	BlockchainTxnRewardV1_Type_value = map[string]int32{
		"securities":      0,
		"data_credits":    1,
		"poc_challengees": 2,
		"poc_challengers": 3,
		"poc_witnesses":   4,
		"consensus":       5,
	}
)

func (x BlockchainTxnRewardV1_Type) Enum() *BlockchainTxnRewardV1_Type {
	p := new(BlockchainTxnRewardV1_Type)
	*p = x
	return p
}

func (x BlockchainTxnRewardV1_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockchainTxnRewardV1_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_txn_rewards_v1_proto_enumTypes[0].Descriptor()
}

func (BlockchainTxnRewardV1_Type) Type() protoreflect.EnumType {
	return &file_blockchain_txn_rewards_v1_proto_enumTypes[0]
}

func (x BlockchainTxnRewardV1_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockchainTxnRewardV1_Type.Descriptor instead.
func (BlockchainTxnRewardV1_Type) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_txn_rewards_v1_proto_rawDescGZIP(), []int{0, 0}
}

type BlockchainTxnRewardV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account []byte                     `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Gateway []byte                     `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Amount  uint64                     `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Type    BlockchainTxnRewardV1_Type `protobuf:"varint,5,opt,name=type,proto3,enum=helium.BlockchainTxnRewardV1_Type" json:"type,omitempty"`
}

func (x *BlockchainTxnRewardV1) Reset() {
	*x = BlockchainTxnRewardV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_txn_rewards_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockchainTxnRewardV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainTxnRewardV1) ProtoMessage() {}

func (x *BlockchainTxnRewardV1) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_txn_rewards_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainTxnRewardV1.ProtoReflect.Descriptor instead.
func (*BlockchainTxnRewardV1) Descriptor() ([]byte, []int) {
	return file_blockchain_txn_rewards_v1_proto_rawDescGZIP(), []int{0}
}

func (x *BlockchainTxnRewardV1) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *BlockchainTxnRewardV1) GetGateway() []byte {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *BlockchainTxnRewardV1) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BlockchainTxnRewardV1) GetType() BlockchainTxnRewardV1_Type {
	if x != nil {
		return x.Type
	}
	return BlockchainTxnRewardV1_securities
}

type BlockchainTxnRewardsV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartEpoch uint64                   `protobuf:"varint,1,opt,name=start_epoch,json=startEpoch,proto3" json:"start_epoch,omitempty"`
	EndEpoch   uint64                   `protobuf:"varint,2,opt,name=end_epoch,json=endEpoch,proto3" json:"end_epoch,omitempty"`
	Rewards    []*BlockchainTxnRewardV1 `protobuf:"bytes,3,rep,name=rewards,proto3" json:"rewards,omitempty"`
}

func (x *BlockchainTxnRewardsV1) Reset() {
	*x = BlockchainTxnRewardsV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_txn_rewards_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockchainTxnRewardsV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainTxnRewardsV1) ProtoMessage() {}

func (x *BlockchainTxnRewardsV1) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_txn_rewards_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainTxnRewardsV1.ProtoReflect.Descriptor instead.
func (*BlockchainTxnRewardsV1) Descriptor() ([]byte, []int) {
	return file_blockchain_txn_rewards_v1_proto_rawDescGZIP(), []int{1}
}

func (x *BlockchainTxnRewardsV1) GetStartEpoch() uint64 {
	if x != nil {
		return x.StartEpoch
	}
	return 0
}

func (x *BlockchainTxnRewardsV1) GetEndEpoch() uint64 {
	if x != nil {
		return x.EndEpoch
	}
	return 0
}

func (x *BlockchainTxnRewardsV1) GetRewards() []*BlockchainTxnRewardV1 {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_blockchain_txn_rewards_v1_proto protoreflect.FileDescriptor

var file_blockchain_txn_rewards_v1_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x78, 0x6e,
	0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x22, 0x97, 0x02, 0x0a, 0x18, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x78, 0x6e, 0x5f, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x5f, 0x76, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x39, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x25, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x78, 0x6e, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f,
	0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x74, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x73, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x70, 0x6f, 0x63, 0x5f, 0x63,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x65, 0x73, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f,
	0x70, 0x6f, 0x63, 0x5f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x10,
	0x03, 0x12, 0x11, 0x0a, 0x0d, 0x70, 0x6f, 0x63, 0x5f, 0x77, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75,
	0x73, 0x10, 0x05, 0x22, 0x95, 0x01, 0x0a, 0x19, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x5f, 0x74, 0x78, 0x6e, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x5f, 0x76,
	0x31, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x45, 0x70, 0x6f,
	0x63, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12,
	0x3a, 0x0a, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x78, 0x6e, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f,
	0x76, 0x31, 0x52, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_blockchain_txn_rewards_v1_proto_rawDescOnce sync.Once
	file_blockchain_txn_rewards_v1_proto_rawDescData = file_blockchain_txn_rewards_v1_proto_rawDesc
)

func file_blockchain_txn_rewards_v1_proto_rawDescGZIP() []byte {
	file_blockchain_txn_rewards_v1_proto_rawDescOnce.Do(func() {
		file_blockchain_txn_rewards_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_blockchain_txn_rewards_v1_proto_rawDescData)
	})
	return file_blockchain_txn_rewards_v1_proto_rawDescData
}

var file_blockchain_txn_rewards_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blockchain_txn_rewards_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blockchain_txn_rewards_v1_proto_goTypes = []interface{}{
	(BlockchainTxnRewardV1_Type)(0), // 0: helium.blockchain_txn_reward_v1.Type
	(*BlockchainTxnRewardV1)(nil),   // 1: helium.blockchain_txn_reward_v1
	(*BlockchainTxnRewardsV1)(nil),  // 2: helium.blockchain_txn_rewards_v1
}
var file_blockchain_txn_rewards_v1_proto_depIdxs = []int32{
	0, // 0: helium.blockchain_txn_reward_v1.type:type_name -> helium.blockchain_txn_reward_v1.Type
	1, // 1: helium.blockchain_txn_rewards_v1.rewards:type_name -> helium.blockchain_txn_reward_v1
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blockchain_txn_rewards_v1_proto_init() }
func file_blockchain_txn_rewards_v1_proto_init() {
	if File_blockchain_txn_rewards_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blockchain_txn_rewards_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockchainTxnRewardV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blockchain_txn_rewards_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockchainTxnRewardsV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blockchain_txn_rewards_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_txn_rewards_v1_proto_goTypes,
		DependencyIndexes: file_blockchain_txn_rewards_v1_proto_depIdxs,
		EnumInfos:         file_blockchain_txn_rewards_v1_proto_enumTypes,
		MessageInfos:      file_blockchain_txn_rewards_v1_proto_msgTypes,
	}.Build()
	File_blockchain_txn_rewards_v1_proto = out.File
	file_blockchain_txn_rewards_v1_proto_rawDesc = nil
	file_blockchain_txn_rewards_v1_proto_goTypes = nil
	file_blockchain_txn_rewards_v1_proto_depIdxs = nil
}
