// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: blockchain_txn_handler.proto

package helium

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_submit RequestType = 0
	RequestType_update RequestType = 1
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "submit",
		1: "update",
	}
	RequestType_value = map[string]int32{
		"submit": 0,
		"update": 1,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_txn_handler_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_blockchain_txn_handler_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_txn_handler_proto_rawDescGZIP(), []int{0}
}

type BlockchainTxnRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type RequestType    `protobuf:"varint,1,opt,name=type,proto3,enum=helium.RequestType" json:"type,omitempty"`
	Key  []byte         `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Txn  *BlockchainTxn `protobuf:"bytes,3,opt,name=txn,proto3" json:"txn,omitempty"`
}

func (x *BlockchainTxnRequestV1) Reset() {
	*x = BlockchainTxnRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_txn_handler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockchainTxnRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainTxnRequestV1) ProtoMessage() {}

func (x *BlockchainTxnRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_txn_handler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainTxnRequestV1.ProtoReflect.Descriptor instead.
func (*BlockchainTxnRequestV1) Descriptor() ([]byte, []int) {
	return file_blockchain_txn_handler_proto_rawDescGZIP(), []int{0}
}

func (x *BlockchainTxnRequestV1) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_submit
}

func (x *BlockchainTxnRequestV1) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BlockchainTxnRequestV1) GetTxn() *BlockchainTxn {
	if x != nil {
		return x.Txn
	}
	return nil
}

type BlockchainTxnInfoV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result             []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Details            []byte `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	Trace              []byte `protobuf:"bytes,3,opt,name=trace,proto3" json:"trace,omitempty"`
	Height             uint64 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	QueuePos           uint32 `protobuf:"varint,5,opt,name=queue_pos,json=queuePos,proto3" json:"queue_pos,omitempty"`
	QueueLen           uint32 `protobuf:"varint,6,opt,name=queue_len,json=queueLen,proto3" json:"queue_len,omitempty"`
	TxnProtocolVersion uint32 `protobuf:"varint,7,opt,name=txn_protocol_version,json=txnProtocolVersion,proto3" json:"txn_protocol_version,omitempty"`
}

func (x *BlockchainTxnInfoV1) Reset() {
	*x = BlockchainTxnInfoV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_txn_handler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockchainTxnInfoV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainTxnInfoV1) ProtoMessage() {}

func (x *BlockchainTxnInfoV1) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_txn_handler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainTxnInfoV1.ProtoReflect.Descriptor instead.
func (*BlockchainTxnInfoV1) Descriptor() ([]byte, []int) {
	return file_blockchain_txn_handler_proto_rawDescGZIP(), []int{1}
}

func (x *BlockchainTxnInfoV1) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BlockchainTxnInfoV1) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *BlockchainTxnInfoV1) GetTrace() []byte {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *BlockchainTxnInfoV1) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockchainTxnInfoV1) GetQueuePos() uint32 {
	if x != nil {
		return x.QueuePos
	}
	return 0
}

func (x *BlockchainTxnInfoV1) GetQueueLen() uint32 {
	if x != nil {
		return x.QueueLen
	}
	return 0
}

func (x *BlockchainTxnInfoV1) GetTxnProtocolVersion() uint32 {
	if x != nil {
		return x.TxnProtocolVersion
	}
	return 0
}

var File_blockchain_txn_handler_proto protoreflect.FileDescriptor

var file_blockchain_txn_handler_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x78, 0x6e,
	0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x1a, 0x14, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x5f, 0x74, 0x78, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x01, 0x0a,
	0x19, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x78, 0x6e, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x76, 0x31, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75,
	0x6d, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x03, 0x74, 0x78, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x78, 0x6e, 0x52, 0x03, 0x74, 0x78, 0x6e,
	0x22, 0xe4, 0x01, 0x0a, 0x16, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f,
	0x74, 0x78, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x76, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x50, 0x6f, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x4c, 0x65, 0x6e, 0x12, 0x30, 0x0a, 0x14, 0x74, 0x78, 0x6e, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x12, 0x74, 0x78, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2a, 0x26, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x01, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blockchain_txn_handler_proto_rawDescOnce sync.Once
	file_blockchain_txn_handler_proto_rawDescData = file_blockchain_txn_handler_proto_rawDesc
)

func file_blockchain_txn_handler_proto_rawDescGZIP() []byte {
	file_blockchain_txn_handler_proto_rawDescOnce.Do(func() {
		file_blockchain_txn_handler_proto_rawDescData = protoimpl.X.CompressGZIP(file_blockchain_txn_handler_proto_rawDescData)
	})
	return file_blockchain_txn_handler_proto_rawDescData
}

var file_blockchain_txn_handler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blockchain_txn_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blockchain_txn_handler_proto_goTypes = []interface{}{
	(RequestType)(0),               // 0: helium.request_type
	(*BlockchainTxnRequestV1)(nil), // 1: helium.blockchain_txn_request_v1
	(*BlockchainTxnInfoV1)(nil),    // 2: helium.blockchain_txn_info_v1
	(*BlockchainTxn)(nil),          // 3: helium.blockchain_txn
}
var file_blockchain_txn_handler_proto_depIdxs = []int32{
	0, // 0: helium.blockchain_txn_request_v1.type:type_name -> helium.request_type
	3, // 1: helium.blockchain_txn_request_v1.txn:type_name -> helium.blockchain_txn
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blockchain_txn_handler_proto_init() }
func file_blockchain_txn_handler_proto_init() {
	if File_blockchain_txn_handler_proto != nil {
		return
	}
	file_blockchain_txn_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_blockchain_txn_handler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockchainTxnRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blockchain_txn_handler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockchainTxnInfoV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blockchain_txn_handler_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_txn_handler_proto_goTypes,
		DependencyIndexes: file_blockchain_txn_handler_proto_depIdxs,
		EnumInfos:         file_blockchain_txn_handler_proto_enumTypes,
		MessageInfos:      file_blockchain_txn_handler_proto_msgTypes,
	}.Build()
	File_blockchain_txn_handler_proto = out.File
	file_blockchain_txn_handler_proto_rawDesc = nil
	file_blockchain_txn_handler_proto_goTypes = nil
	file_blockchain_txn_handler_proto_depIdxs = nil
}
