// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: blockchain_txn_poc_receipts_v2.proto

package helium

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockchainTxnPocReceiptsV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Challenger   []byte                        `protobuf:"bytes,1,opt,name=challenger,proto3" json:"challenger,omitempty"`
	Secret       []byte                        `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	OnionKeyHash []byte                        `protobuf:"bytes,3,opt,name=onion_key_hash,json=onionKeyHash,proto3" json:"onion_key_hash,omitempty"`
	Path         []*BlockchainPocPathElementV1 `protobuf:"bytes,4,rep,name=path,proto3" json:"path,omitempty"`
	Fee          uint64                        `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`
	Signature    []byte                        `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	BlockHash    []byte                        `protobuf:"bytes,7,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// used for off-chain poc replay prevention
	Timestamp uint64 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *BlockchainTxnPocReceiptsV2) Reset() {
	*x = BlockchainTxnPocReceiptsV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_txn_poc_receipts_v2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockchainTxnPocReceiptsV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainTxnPocReceiptsV2) ProtoMessage() {}

func (x *BlockchainTxnPocReceiptsV2) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_txn_poc_receipts_v2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainTxnPocReceiptsV2.ProtoReflect.Descriptor instead.
func (*BlockchainTxnPocReceiptsV2) Descriptor() ([]byte, []int) {
	return file_blockchain_txn_poc_receipts_v2_proto_rawDescGZIP(), []int{0}
}

func (x *BlockchainTxnPocReceiptsV2) GetChallenger() []byte {
	if x != nil {
		return x.Challenger
	}
	return nil
}

func (x *BlockchainTxnPocReceiptsV2) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *BlockchainTxnPocReceiptsV2) GetOnionKeyHash() []byte {
	if x != nil {
		return x.OnionKeyHash
	}
	return nil
}

func (x *BlockchainTxnPocReceiptsV2) GetPath() []*BlockchainPocPathElementV1 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *BlockchainTxnPocReceiptsV2) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *BlockchainTxnPocReceiptsV2) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *BlockchainTxnPocReceiptsV2) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *BlockchainTxnPocReceiptsV2) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_blockchain_txn_poc_receipts_v2_proto protoreflect.FileDescriptor

var file_blockchain_txn_poc_receipts_v2_proto_rawDesc = []byte{
	0x0a, 0x24, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x78, 0x6e,
	0x5f, 0x70, 0x6f, 0x63, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x5f, 0x76, 0x32,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x1a, 0x1c,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x70, 0x6f, 0x63, 0x5f, 0x63,
	0x6f, 0x72, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x02, 0x0a,
	0x1e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x78, 0x6e, 0x5f,
	0x70, 0x6f, 0x63, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x5f, 0x76, 0x32, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x6f, 0x6e, 0x69, 0x6f, 0x6e,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x6f, 0x6e, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x3a, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x68, 0x65,
	0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f,
	0x70, 0x6f, 0x63, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x76, 0x31, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blockchain_txn_poc_receipts_v2_proto_rawDescOnce sync.Once
	file_blockchain_txn_poc_receipts_v2_proto_rawDescData = file_blockchain_txn_poc_receipts_v2_proto_rawDesc
)

func file_blockchain_txn_poc_receipts_v2_proto_rawDescGZIP() []byte {
	file_blockchain_txn_poc_receipts_v2_proto_rawDescOnce.Do(func() {
		file_blockchain_txn_poc_receipts_v2_proto_rawDescData = protoimpl.X.CompressGZIP(file_blockchain_txn_poc_receipts_v2_proto_rawDescData)
	})
	return file_blockchain_txn_poc_receipts_v2_proto_rawDescData
}

var file_blockchain_txn_poc_receipts_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blockchain_txn_poc_receipts_v2_proto_goTypes = []interface{}{
	(*BlockchainTxnPocReceiptsV2)(nil), // 0: helium.blockchain_txn_poc_receipts_v2
	(*BlockchainPocPathElementV1)(nil), // 1: helium.blockchain_poc_path_element_v1
}
var file_blockchain_txn_poc_receipts_v2_proto_depIdxs = []int32{
	1, // 0: helium.blockchain_txn_poc_receipts_v2.path:type_name -> helium.blockchain_poc_path_element_v1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blockchain_txn_poc_receipts_v2_proto_init() }
func file_blockchain_txn_poc_receipts_v2_proto_init() {
	if File_blockchain_txn_poc_receipts_v2_proto != nil {
		return
	}
	file_blockchain_poc_core_v1_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_blockchain_txn_poc_receipts_v2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockchainTxnPocReceiptsV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blockchain_txn_poc_receipts_v2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_txn_poc_receipts_v2_proto_goTypes,
		DependencyIndexes: file_blockchain_txn_poc_receipts_v2_proto_depIdxs,
		MessageInfos:      file_blockchain_txn_poc_receipts_v2_proto_msgTypes,
	}.Build()
	File_blockchain_txn_poc_receipts_v2_proto = out.File
	file_blockchain_txn_poc_receipts_v2_proto_rawDesc = nil
	file_blockchain_txn_poc_receipts_v2_proto_goTypes = nil
	file_blockchain_txn_poc_receipts_v2_proto_depIdxs = nil
}
