// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: blockchain_gossip_handler.proto

package helium

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockchainGossipBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From   []byte `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Block  []byte `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	Hash   []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Height uint64 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *BlockchainGossipBlock) Reset() {
	*x = BlockchainGossipBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_gossip_handler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockchainGossipBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainGossipBlock) ProtoMessage() {}

func (x *BlockchainGossipBlock) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_gossip_handler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainGossipBlock.ProtoReflect.Descriptor instead.
func (*BlockchainGossipBlock) Descriptor() ([]byte, []int) {
	return file_blockchain_gossip_handler_proto_rawDescGZIP(), []int{0}
}

func (x *BlockchainGossipBlock) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *BlockchainGossipBlock) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *BlockchainGossipBlock) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BlockchainGossipBlock) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_blockchain_gossip_handler_proto protoreflect.FileDescriptor

var file_blockchain_gossip_handler_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x67, 0x6f, 0x73,
	0x73, 0x69, 0x70, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6f, 0x0a, 0x17, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f,
	0x67, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blockchain_gossip_handler_proto_rawDescOnce sync.Once
	file_blockchain_gossip_handler_proto_rawDescData = file_blockchain_gossip_handler_proto_rawDesc
)

func file_blockchain_gossip_handler_proto_rawDescGZIP() []byte {
	file_blockchain_gossip_handler_proto_rawDescOnce.Do(func() {
		file_blockchain_gossip_handler_proto_rawDescData = protoimpl.X.CompressGZIP(file_blockchain_gossip_handler_proto_rawDescData)
	})
	return file_blockchain_gossip_handler_proto_rawDescData
}

var file_blockchain_gossip_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blockchain_gossip_handler_proto_goTypes = []interface{}{
	(*BlockchainGossipBlock)(nil), // 0: blockchain_gossip_block
}
var file_blockchain_gossip_handler_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blockchain_gossip_handler_proto_init() }
func file_blockchain_gossip_handler_proto_init() {
	if File_blockchain_gossip_handler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blockchain_gossip_handler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockchainGossipBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blockchain_gossip_handler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_gossip_handler_proto_goTypes,
		DependencyIndexes: file_blockchain_gossip_handler_proto_depIdxs,
		MessageInfos:      file_blockchain_gossip_handler_proto_msgTypes,
	}.Build()
	File_blockchain_gossip_handler_proto = out.File
	file_blockchain_gossip_handler_proto_rawDesc = nil
	file_blockchain_gossip_handler_proto_goTypes = nil
	file_blockchain_gossip_handler_proto_depIdxs = nil
}
