// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: blockchain_txn_add_subnetwork_v1.proto

package helium

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockchainTxnAddSubnetworkV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenType           BlockchainTokenTypeV1 `protobuf:"varint,1,opt,name=token_type,json=tokenType,proto3,enum=helium.BlockchainTokenTypeV1" json:"token_type,omitempty"`
	SubnetworkKey       []byte                `protobuf:"bytes,2,opt,name=subnetwork_key,json=subnetworkKey,proto3" json:"subnetwork_key,omitempty"`
	RewardServerKeys    [][]byte              `protobuf:"bytes,3,rep,name=reward_server_keys,json=rewardServerKeys,proto3" json:"reward_server_keys,omitempty"`
	Premine             uint64                `protobuf:"varint,4,opt,name=premine,proto3" json:"premine,omitempty"`
	NetworkSignature    []byte                `protobuf:"bytes,5,opt,name=network_signature,json=networkSignature,proto3" json:"network_signature,omitempty"`
	SubnetworkSignature []byte                `protobuf:"bytes,6,opt,name=subnetwork_signature,json=subnetworkSignature,proto3" json:"subnetwork_signature,omitempty"`
}

func (x *BlockchainTxnAddSubnetworkV1) Reset() {
	*x = BlockchainTxnAddSubnetworkV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_txn_add_subnetwork_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockchainTxnAddSubnetworkV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainTxnAddSubnetworkV1) ProtoMessage() {}

func (x *BlockchainTxnAddSubnetworkV1) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_txn_add_subnetwork_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainTxnAddSubnetworkV1.ProtoReflect.Descriptor instead.
func (*BlockchainTxnAddSubnetworkV1) Descriptor() ([]byte, []int) {
	return file_blockchain_txn_add_subnetwork_v1_proto_rawDescGZIP(), []int{0}
}

func (x *BlockchainTxnAddSubnetworkV1) GetTokenType() BlockchainTokenTypeV1 {
	if x != nil {
		return x.TokenType
	}
	return BlockchainTokenTypeV1_hnt
}

func (x *BlockchainTxnAddSubnetworkV1) GetSubnetworkKey() []byte {
	if x != nil {
		return x.SubnetworkKey
	}
	return nil
}

func (x *BlockchainTxnAddSubnetworkV1) GetRewardServerKeys() [][]byte {
	if x != nil {
		return x.RewardServerKeys
	}
	return nil
}

func (x *BlockchainTxnAddSubnetworkV1) GetPremine() uint64 {
	if x != nil {
		return x.Premine
	}
	return 0
}

func (x *BlockchainTxnAddSubnetworkV1) GetNetworkSignature() []byte {
	if x != nil {
		return x.NetworkSignature
	}
	return nil
}

func (x *BlockchainTxnAddSubnetworkV1) GetSubnetworkSignature() []byte {
	if x != nil {
		return x.SubnetworkSignature
	}
	return nil
}

var File_blockchain_txn_add_subnetwork_v1_proto protoreflect.FileDescriptor

var file_blockchain_txn_add_subnetwork_v1_proto_rawDesc = []byte{
	0x0a, 0x26, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x78, 0x6e,
	0x5f, 0x61, 0x64, 0x64, 0x5f, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f,
	0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d,
	0x1a, 0x1e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb2, 0x02, 0x0a, 0x20, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f,
	0x74, 0x78, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x5f, 0x76, 0x31, 0x12, 0x3f, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x68, 0x65, 0x6c, 0x69,
	0x75, 0x6d, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x76, 0x31, 0x52, 0x09, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d,
	0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4b, 0x65, 0x79, 0x12, 0x2c, 0x0a,
	0x12, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6b,
	0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x10, 0x72, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x72, 0x65, 0x6d, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x70, 0x72,
	0x65, 0x6d, 0x69, 0x6e, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x10, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x31, 0x0a, 0x14, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x13, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blockchain_txn_add_subnetwork_v1_proto_rawDescOnce sync.Once
	file_blockchain_txn_add_subnetwork_v1_proto_rawDescData = file_blockchain_txn_add_subnetwork_v1_proto_rawDesc
)

func file_blockchain_txn_add_subnetwork_v1_proto_rawDescGZIP() []byte {
	file_blockchain_txn_add_subnetwork_v1_proto_rawDescOnce.Do(func() {
		file_blockchain_txn_add_subnetwork_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_blockchain_txn_add_subnetwork_v1_proto_rawDescData)
	})
	return file_blockchain_txn_add_subnetwork_v1_proto_rawDescData
}

var file_blockchain_txn_add_subnetwork_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blockchain_txn_add_subnetwork_v1_proto_goTypes = []interface{}{
	(*BlockchainTxnAddSubnetworkV1)(nil), // 0: helium.blockchain_txn_add_subnetwork_v1
	(BlockchainTokenTypeV1)(0),           // 1: helium.blockchain_token_type_v1
}
var file_blockchain_txn_add_subnetwork_v1_proto_depIdxs = []int32{
	1, // 0: helium.blockchain_txn_add_subnetwork_v1.token_type:type_name -> helium.blockchain_token_type_v1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blockchain_txn_add_subnetwork_v1_proto_init() }
func file_blockchain_txn_add_subnetwork_v1_proto_init() {
	if File_blockchain_txn_add_subnetwork_v1_proto != nil {
		return
	}
	file_blockchain_token_type_v1_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_blockchain_txn_add_subnetwork_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockchainTxnAddSubnetworkV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blockchain_txn_add_subnetwork_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_txn_add_subnetwork_v1_proto_goTypes,
		DependencyIndexes: file_blockchain_txn_add_subnetwork_v1_proto_depIdxs,
		MessageInfos:      file_blockchain_txn_add_subnetwork_v1_proto_msgTypes,
	}.Build()
	File_blockchain_txn_add_subnetwork_v1_proto = out.File
	file_blockchain_txn_add_subnetwork_v1_proto_rawDesc = nil
	file_blockchain_txn_add_subnetwork_v1_proto_goTypes = nil
	file_blockchain_txn_add_subnetwork_v1_proto_depIdxs = nil
}
