// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: price_report.proto

package helium

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceReportV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// / The price, specified in 1/1000000ths of a cent, i.e. 1$ = 1000000.
	// / NOTE: Helium blockchain specifies $1 = 10^8, whereas on solana only 10^6
	// / is supported.
	Price uint64 `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	// / The timestamp for this report (unix epoch)
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// / The token type for this report
	TokenType BlockchainTokenTypeV1 `protobuf:"varint,3,opt,name=token_type,json=tokenType,proto3,enum=helium.BlockchainTokenTypeV1" json:"token_type,omitempty"`
}

func (x *PriceReportV1) Reset() {
	*x = PriceReportV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_report_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceReportV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceReportV1) ProtoMessage() {}

func (x *PriceReportV1) ProtoReflect() protoreflect.Message {
	mi := &file_price_report_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceReportV1.ProtoReflect.Descriptor instead.
func (*PriceReportV1) Descriptor() ([]byte, []int) {
	return file_price_report_proto_rawDescGZIP(), []int{0}
}

func (x *PriceReportV1) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceReportV1) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PriceReportV1) GetTokenType() BlockchainTokenTypeV1 {
	if x != nil {
		return x.TokenType
	}
	return BlockchainTokenTypeV1_hnt
}

var File_price_report_proto protoreflect.FileDescriptor

var file_price_report_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x1a, 0x1e, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a,
	0x0f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x76, 0x31,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x3f, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75,
	0x6d, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x76, 0x31, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_price_report_proto_rawDescOnce sync.Once
	file_price_report_proto_rawDescData = file_price_report_proto_rawDesc
)

func file_price_report_proto_rawDescGZIP() []byte {
	file_price_report_proto_rawDescOnce.Do(func() {
		file_price_report_proto_rawDescData = protoimpl.X.CompressGZIP(file_price_report_proto_rawDescData)
	})
	return file_price_report_proto_rawDescData
}

var file_price_report_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_price_report_proto_goTypes = []interface{}{
	(*PriceReportV1)(nil),      // 0: helium.price_report_v1
	(BlockchainTokenTypeV1)(0), // 1: helium.blockchain_token_type_v1
}
var file_price_report_proto_depIdxs = []int32{
	1, // 0: helium.price_report_v1.token_type:type_name -> helium.blockchain_token_type_v1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_price_report_proto_init() }
func file_price_report_proto_init() {
	if File_price_report_proto != nil {
		return
	}
	file_blockchain_token_type_v1_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_price_report_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceReportV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_price_report_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_price_report_proto_goTypes,
		DependencyIndexes: file_price_report_proto_depIdxs,
		MessageInfos:      file_price_report_proto_msgTypes,
	}.Build()
	File_price_report_proto = out.File
	file_price_report_proto_rawDesc = nil
	file_price_report_proto_goTypes = nil
	file_price_report_proto_depIdxs = nil
}
