// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: reward_manifest.proto

package helium

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RewardManifest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WrittenFiles []string `protobuf:"bytes,1,rep,name=written_files,json=writtenFiles,proto3" json:"written_files,omitempty"`
	// Unix timestamp in seconds of the start of the inventory period
	StartTimestamp uint64 `protobuf:"varint,2,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	// Unix timestamp in seconds of the end of the inventory period
	EndTimestamp uint64 `protobuf:"varint,3,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
}

func (x *RewardManifest) Reset() {
	*x = RewardManifest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reward_manifest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RewardManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardManifest) ProtoMessage() {}

func (x *RewardManifest) ProtoReflect() protoreflect.Message {
	mi := &file_reward_manifest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardManifest.ProtoReflect.Descriptor instead.
func (*RewardManifest) Descriptor() ([]byte, []int) {
	return file_reward_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *RewardManifest) GetWrittenFiles() []string {
	if x != nil {
		return x.WrittenFiles
	}
	return nil
}

func (x *RewardManifest) GetStartTimestamp() uint64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *RewardManifest) GetEndTimestamp() uint64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

var File_reward_manifest_proto protoreflect.FileDescriptor

var file_reward_manifest_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x22,
	0x84, 0x01, 0x0a, 0x0f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x6d, 0x61, 0x6e, 0x69, 0x66,
	0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x77, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x5f, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x72, 0x69, 0x74,
	0x74, 0x65, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reward_manifest_proto_rawDescOnce sync.Once
	file_reward_manifest_proto_rawDescData = file_reward_manifest_proto_rawDesc
)

func file_reward_manifest_proto_rawDescGZIP() []byte {
	file_reward_manifest_proto_rawDescOnce.Do(func() {
		file_reward_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(file_reward_manifest_proto_rawDescData)
	})
	return file_reward_manifest_proto_rawDescData
}

var file_reward_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_reward_manifest_proto_goTypes = []interface{}{
	(*RewardManifest)(nil), // 0: helium.reward_manifest
}
var file_reward_manifest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reward_manifest_proto_init() }
func file_reward_manifest_proto_init() {
	if File_reward_manifest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reward_manifest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RewardManifest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reward_manifest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reward_manifest_proto_goTypes,
		DependencyIndexes: file_reward_manifest_proto_depIdxs,
		MessageInfos:      file_reward_manifest_proto_msgTypes,
	}.Build()
	File_reward_manifest_proto = out.File
	file_reward_manifest_proto_rawDesc = nil
	file_reward_manifest_proto_goTypes = nil
	file_reward_manifest_proto_depIdxs = nil
}
